### ISSUE TITLE
"serve static assets" config property renamed?

### ISSUE THREAD

**Issue by itsdevdom** [ricwein/gitlab-uberspace-tutorial#10]
In the GitLab production config file at `config/environments/production.rb`, the following configuration property doesn't exist:

<pre>config.serve_static_assets = true</pre>

I am shure that some GitLab versions ago it did, but now it's gone. Maybe it is the same as the following (so did they just rename the configuration property)?

<pre>config.serve_static_files = true</pre>

**Comment by ricwein** [comment]
I've changed the line. Thank you!
