### ISSUE TITLE
Installation von CMake

### ISSUE THREAD

**Issue by fgladisch** [ricwein/gitlab-uberspace-tutorial#13]
`toast arm cmake` schlug leider bei mir mit `can't find cmake` fehl. Alternativ kann cmake auch mit

`toast arm https://cmake.org/files/v3.5/cmake-3.5.1.tar.gz`

installiert werden (vorher die Version im Befehl aktualisieren).

**Comment by Lazalatin** [comment]
:+1:  
Danke für den Hinweis. Ich würde auch empfehlen dies ins Tutorial aufzunehmen.

**Comment by klml** [comment]
@fgladisch das ist damit doch mit https://github.com/ricwein/gitlab-uberspace-tutorial/commit/8f68014839c7940756cf75c8a8cd104968524cf0#diff-1e290ac8433d555bce009b162cb869d0R62 auch gefixt, oder? danke @ricwein

**Comment by ricwein** [comment]
Ein entsprechender Hinweise wurde damit zumindest hinzugefügt, auch wenn erstmal auf eine ältere cmake Version verwiesen wird.
