### ISSUE TITLE
An error occurred while installing rugged (0.23.3), and Bundler cannot continue.

### ISSUE THREAD

**Issue by Nevergonnachange** [ricwein/gitlab-uberspace-tutorial#14]
When running

`bundle install --deployment --without development test postgres aws`

I get an error:

`
An error occurred while installing rugged (0.23.3), and Bundler cannot continue.
Make sure that gem install rugged -v '0.23.3' succeeds before bundling.
`

**Comment by Nevergonnachange** [comment]
solved by running:

`toast arm https://cmake.org/files/v3.5/cmake-3.5.1.tar.gz`

**Comment by ricwein** [comment]
Danke für den Hinweis. Ist aber im Grunde bereits mit #13 abgehandelt.
