### ISSUE TITLE
[your gitlab-workhorse port] vs. [your git-http port]

### ISSUE THREAD

**Issue by klml** [ricwein/gitlab-uberspace-tutorial#16]
[GitLab als Uberspace-Service verwalten](https://github.com/ricwein/gitlab-uberspace-tutorial#gitlab-als-uberspace-service-verwalten) sagt:

> In dem Script sind am Anfang zwei Ports anzugeben.  [...] 2. Für [your gitlab-workhorse port] suchen wir uns...

doch leider finde ich im [Script](https://github.com/ricwein/gitlab-uberspace-tutorial/blob/master/services/gitlab-workhorse) kein [your gitlab-workhorse port], damit ist vermutlich die "http_port=[your git-http port]" gemeint? Auswirkungen hat das afaik keine, da es eh nur eine script-variable ist, aber man sucht halt erst mal.

Wenn ja mach ich gern ein PR.

Ich kann das leider nicht ausprobieren, weil bei mir beides, "gitlab_workhorse_port" oder  "http_port" nicht funktioniert.

**Comment by ricwein** [comment]
Du hast natürlich recht. Es sollte sich bei dem besagten Port um den Workhorse-Port handeln. Anfangs hieß Workhorse nur git-http. Inzwischen stimmt das natürlich nicht mehr. Ich habe soeben einen Fix mit 8f68014839c7940756cf75c8a8cd104968524cf0 commited.

Es handelt sich bei den Ports in den eckigen Klammer im Übrigen zwar um Variablen, diese müssen jedoch bitte per Hand durch die entsprechenden Werte ersetzt werden. Auch im git-workhorse [Script](https://github.com/ricwein/gitlab-uberspace-tutorial/blob/master/services/gitlab-workhorse), damit der Service nach dem Start auch auf den gewünschten Port lauscht.

Danke für die Meldung!

**Comment by klml** [comment]
Dank dir, vor allem für die schnelle Reaktion;)
