### ISSUE TITLE
git_path vs. bin_path

### ISSUE THREAD

**Issue by klml** [ricwein/gitlab-uberspace-tutorial#17]
[gitlab.yml Konfiguration](https://github.com/ricwein/gitlab-uberspace-tutorial#gitlabyml-konfiguration) sagt

> Der git_path sollte stimmen, falls git per Toast installiert wurde.

das soll der "bin_path" heißen? "bin_path" füht ja zu git

**Comment by ricwein** [comment]
Da hast du mich ertappt. `bin_path` wäre an der Stelle natürlich korrekt. Der Eintrag gehört ja sowieso zur Kategorie _git_. Ich habe die entsprechende Zeile angepasst.

**Comment by klml** [comment]
da geht's gar nicht ums ertappen. Ich bin ja heilfroh das es Dein manual gibt, sonst wäre ich aufgeschmissen;) Als gem und ruby Anfänger stolpere ich halt leichter über Dinge die jemand routinierten gar nicht mehr auffallen.
