### ISSUE TITLE
Assets haben 403 (Forbidden)

### ISSUE THREAD

**Issue by 5minpause** [ricwein/gitlab-uberspace-tutorial#2]
Hi danke fuer die Anleitung.

Leider hat mein public/assets Folder ein 403 und dadurch bekomme ich keine Assets.
Muss ich Apache anders konfigurieren?

Danke.

**Comment by 5minpause** [comment]
Habe mein Problem anders gelöst. Warum am Ende des Tutorials jedoch ein 403 auf `public/assets` kam, bleibt mir unerklärlich.

**Comment by ricwein** [comment]
Hattest du in der  `config/environments/production.rb` die Zeile `config.serve_static_assets = false` auf `true` umgestellt? Dies ist nötig um den Unicorn-Server das directe ausliefern der assets an unseren proxy zu erlauben.

``` ruby
config.serve_static_assets = true
```

**Comment by 5minpause** [comment]
Ja das hatte ich gemacht.
