### ISSUE TITLE
Rollback

### ISSUE THREAD

**Issue by Lapsus** [ricwein/gitlab-uberspace-tutorial#20]
Hi,

du erläuterst zwar wie man vor einem Upgrade ein Backup erstellt, wie man aber den Rollback macht, nicht. Vielleicht kannst du das noch ergänzen, das wäre super.

Viele Grüße
Dirk

**Comment by ricwein** [comment]
Backups einspielen läuft wie in der Doku auf [gitlab.com](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/raketasks/backup_restore.md#restore-a-previously-created-backup) ab.

``` bash
cd ~/gitlab
bundle exec rake gitlab:backup:restore RAILS_ENV=production
svc -du ~/service/gitlab && svc -du ~/service/sidekiq && svc -du ~/service/gitlab-workhorse
```

Alternativ lässt sich noch über den `BACKUP` parameter bestimmen, ob ein konkretes Backup (anhand des Dateinamen) eingespielt werden soll. Das sähe dann in etwa so aus:

``` bash
cd ~/gitlab
bundle exec rake gitlab:backup:restore BACKUP=1393513186
svc -du ~/service/gitlab && svc -du ~/service/sidekiq && svc -du ~/service/gitlab-workhorse
```

**Comment by Lapsus** [comment]
perfekt danke. das hab ich gesucht und nicht gefunden.
