### ISSUE TITLE
Warteschlange wird nicht abgearbeitet

### ISSUE THREAD

**Issue by eknoes** [ricwein/gitlab-uberspace-tutorial#27]
Ich habe mich gewundert, warum die Warteschlange (sidekiq) nicht abgearbeitet wurde (Unter Admin View → Monitoring → Background Jobs). 

Nachdem ich das sidekiq Service File angepasst habe, und alle Queues hinzugefügt habe, funktioniert es. Dies sollte vielleicht dokumentiert werden, doch vorher hätte ich gern eine Bestätigung, dass das die beste Lösung ist:

`exec bundle exec sidekiq -q authorized_projects -q build -q clear_database_cache -q cronjob -q default -q delete_merged_branches -q delete_user -q email_receiver -q emails_on_push -q expire_build_instance_artifacts -q git_garbage_collect -q gitlab_shell -q group_destroy -q irker -q mailers -q merge -q new_note -q pipeline -q post_receive -q process_commit -q project_cache -q project_destroy -q project_export -q project_service -q project_web_hook -q reactive_caching -q repository_check -q repository_fork -q repository_import -q system_hook -q update_merge_requests -q use_key -e $RAILS_ENV -P $sidekiq_pidfile >> $sidekiq_logfile 2>&1`

Kurz: Alle fehlenden Warteschlangen mit einem -q ergänzt. Gibt es da einen besseren Ansatz?

**Comment by sauberfred** [comment]
Da die ganzen Queues auch in der Datei `gitlab/config/sidekiq_queues.yml` stehen, habe ich meinen sidekiq Dienst wie folgt angepasst:
```bash
export RAILS_ENV="production"
export GITLAB_PATH="$HOME/gitlab"

cd $GITLAB_PATH/
app_root=$GITLAB_PATH
sidekiq_pidfile="$app_root/tmp/pids/sidekiq.pid"
sidekiq_logfile="$app_root/log/sidekiq.log"
sidekiq_config="$app_root/config/sidekiq_queues.yml"

exec bundle exec sidekiq -C "${sidekiq_config}" -e $RAILS_ENV -P $sidekiq_pidfile >> $sidekiq_logfile 2>&1
```

So stand das im init.d script von Gitlab.
Funktioniert bis jetzt auch einwandfrei und hat den Vorteil dass sollten in Zukunft noch weiter Queues hinzukommen diese nicht manuell hinzugefügt werden müssen.
