### ISSUE TITLE
Git Aktualisierung von kernel.org

### ISSUE THREAD

**Issue by Eorlariel** [ricwein/gitlab-uberspace-tutorial#3]
Die Git Installation bzw das Upgrade mittels toast kann scheitern, wenn es von github kommt.
das kernel.org tar hat jedoch die nötigen config-Dateien für toast.

Schlage deshalb vor dies zu verwenden:

toast arm https://www.kernel.org/pub/software/scm/git/git-2.6.2.tar.gz

**Comment by ricwein** [comment]
danke für den Hinweis. Ich habe den entsprechenden Eintrag angepasst.
