### ISSUE TITLE
Webpack compile

### ISSUE THREAD

**Issue by ssteinhauser** [ricwein/gitlab-uberspace-tutorial#32]
After the installation of nodejs and webpack it was additionally required to run the following command:
```bash
$ bundle exec rake webpack:compile RAILS_ENV=production
```

It would be great to add this to the documentation.

**Comment by pascaliske** [comment]
You should not run the rake task `webpack:compile` directly.
For compiling the assets you just want to run the task `gitlab:assets:compile`, because the `gitlab:assets:compile` internally runs the `webpack:compile`.

(see https://gitlab.com/gitlab-org/gitlab-ce/issues/28759#note_25184020)

**Comment by ricwein** [comment]
@pascaliske is correct. Thanks for the gitlab-issue link.

In addition, the mentioned `gitlab:assets:compile` command was already added with #31 some days ago.
