### ISSUE TITLE
Some more access right mods

### ISSUE THREAD

**Issue by Eorlariel** [ricwein/gitlab-uberspace-tutorial#4]
Das repository directory musste folgende Berechtigungen im Nachhinein noch erhalten:

chmod g+ws repositories
chmod o-rwx repositories

**Comment by ricwein** [comment]
Die Hinweise sollte auch vom `rake gitlab:check` script kommen, aber ist natürlich richtig. Ich habe entsprechende Hinweise hinzugefügt.

**Comment by Eorlariel** [comment]
Es kam vom gitlab:check, ist aber so für andere Nutzer einfacher
