### ISSUE TITLE
Gitlab-Git-HTTP-Server aka. Gitlab Workhorse nicht auf CentOS-5-Hosts

### ISSUE THREAD

**Issue by bbbenjie** [ricwein/gitlab-uberspace-tutorial#6]
Hallo @ricwein,
seit Gitlab 8.2 heißt der HTTP-Server nun "Gitlab Workhorse".
Vielleicht kannst du in deiner Anleitung erwähnen, dass die Installation des Servers wegen des benötigten Go 1.5 auf CentOS-5-Hosts nicht funktionieren wird?
Siehe https://wiki.uberspace.de/development:golang

Gruß bbbenjie

**Comment by ricwein** [comment]
Ich habe eine entsprechenden Hinweis hinzugefügt. Dankeschön!
