### ISSUE TITLE
Download als .zip nicht möglich

### ISSUE THREAD

**Issue by damadmai** [ricwein/gitlab-uberspace-tutorial#8]
Falls noch jemand seit #7 auch über das Problem stolpert, dass beim Versuch ein Projekt als .zip downzuloaden stattdessen ein JSON angezeigt wird:
https://gitlab.com/gitlab-org/gitlab-ce/issues/4165
Hier ist das Problem genauer beschrieben, doch leider wurde noch keine Lösung gefunden.

**Comment by bbbenjie** [comment]
Die betroffene Rewrite-Rule aus der Anleitung von ricwein muss folgendermaßen lauten, damit das Gitlab Workhorse den Download übernimmt:

`# redirect http-git requests to gitlab-workhorse`
`RewriteCond %{REQUEST_URI} .*\.(git|zip)`

**Comment by ricwein** [comment]
Die angesprochene Korrektur des Apache-redirect sollte das Problem tatsächlich beheben. Leider kann ich es selber momentan nicht testen, kann es jemand bestätigen? @damadmai

**Comment by damadmai** [comment]
Habe es getestet, funktioniert.
Super, besten Dank @bbbenjie

**Comment by damadmai** [comment]
Der .zip-Download funktioniert nun zwar, jedoch seit GitLab 8.6 der Download von einzelnen Files nicht mehr. Es liegt wieder mal an der .htaccess.
Mit folgenden RewriteConditions für `gitlab-workhorse` funktioniert es:

```
RewriteCond %{REQUEST_URI} .*\.(git|zip) [OR]
RewriteCond %{REQUEST_URI} .*/raw/
```

Jedoch weiß ich nicht, ob das eine "schöne" zukunftssichere Lösung ist bzw. ob das so gedacht ist.
Findet evtl. jemand in der offiziellen Doku die Stelle, wo steht, wann an `unicorn` & wann an `gitlab-workhorse`(ehem. `git-http-server`) die Anfragen zu schicken sind?

**Comment by damadmai** [comment]
In der offiziellen [Apache-Konfigurationsdatei](https://gitlab.com/gitlab-org/gitlab-recipes/blob/master/web-server/apache/gitlab-ssl-apache22.conf) wurde es nicht viel anders gemacht, wobei es damit zwar funktioniert die Dateien downzuloaden, jedoch nicht mehr die grafische Oberfläche zu benutzen, weil git-workhorse dafür fälschlicherweise aufgerufen wird.
Bitte austesten, ob es bei Euch auch so, wie in meinem Pull-Request #15 funktioniert.

Ganz allgemein sind beim Updaten diese Hinweise empfehlenswert:
https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update

**Comment by joa77** [comment]
Unter gitlab 8.3.10 funktioniert der download als zip leider schon wieder nicht.
https://[domain]/[usr]/[repo]/repository/archive.zip?ref=master für zu folgendem JSON String im Browser:

```
{"RepoPath":"/home/[uberspaceuser]/repositories/[user]/[repo].git","ArchivePrefix":"[repo]-master-[commitID]","ArchivePath":"/home/[uberspaceuser]/gitlab/shared/cache/archive/[repo].git/[repo]-master-[commitID].zip","CommitId":"[commitID]"}
```
